### ISSUE TITLE
Parfois la même traduction apparaît deux fois sur une carte.

### ISSUE THREAD

**Issue by fandolfatto** [laurentbarraud/Snowlexi#41]
[Doc2.docx](https://github.com/laurentbarraud/Snowlexi/files/4419456/Doc2.docx)

**Comment by laurentbarraud** [comment]
Corrigé par l'ajout d'une fonction de "sleep" du thread actif.
Lors de l'exécution de la boucle qui fait appel à une requête SQL de lecture d'une traduction, celle-ci s'exécutait trop vite pour que le paramètre de pseudo-hasard RAND ne réutilise pas le même id.

**Comment by laurentbarraud** [comment]
Faire appel à la fonction de hasard une deuxième fois, si deux réponses du QCM sont identiques.
